name: coolingo
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=10.2
  - pytorch=1.7.0
  - torchvision=0.8.1
  - numpy=1.19.2
  - pip:
      - albumentations==0.4.3
      - opencv-python==4.1.2.30
      - pudb==2019.2
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.2
      - pytorch-lightning==1.0.8
      - omegaconf==2.0.0
      - test-tube>=0.7.5
      - streamlit>=0.73.1
      - einops==0.3.0
      - transformers==4.3.1
      - tensorflow==2.3.1
      - scipy==0.19.0
      - numba==0.48
      - librosa==0.7.2
      - phonemizer>=2.2.0
      - unidecode==0.4.20
      - tensorboardX
      - matplotlib
      - Pillow
      - flask
      - tqdm
      - inflect
      - bokeh==1.4.0
      - pysbd
      - pyworld
      - soundfile
      - nose==1.3.7
      - cardboardlint==1.3.0
      - pylint==2.5.3
      - gdown
      - umap-learn
      - cython
      - pyyaml
      - -e .
      - tts
# conda env create -f environment.yaml

